apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${DEPLOY_ENV}-w-p-inact-users-checkup-cron-job
  namespace: termodom-namespace
spec:
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ${DEPLOY_ENV}-td-w-p-inact-users-checkup-cron-job
              image: limitlesssoft/web-public-inactive-users-checkup-cron-job:${DEPLOY_ENV}
              imagePullPolicy: Always
              env:
                - name: VAULT_URI
                  value: "${VAULT_URI}"
                - name: VAULT_USERNAME
                  value: "${VAULT_USERNAME}"
                - name: VAULT_PASSWORD
                  value: "${VAULT_PASSWORD}"
                - name: VAULT_ENGINE
                  value: "${VAULT_ENGINE}"
                - name: VAULT_PATH
                  value: "${VAULT_PATH}"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred