apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${DEPLOY_ENV}-parametri-danas-update-cron-job
  namespace: termodom-namespace
spec:
  schedule: "0 0-4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ${DEPLOY_ENV}-parametri-danas-update-cron-job-container
              image: limitlesssoft/termodom-parametri-danas-update-cron-job:${DEPLOY_ENV}
              imagePullPolicy: Always
              env:
                - name: DEPLOY_ENV
                  value: "${DEPLOY_ENV}"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred