name: Release office public BE applications

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  build-and-push-office-public-api:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/office/public-be/build-and-push-images/office-public-api-build-and-push-image.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      
  deploy-office-public-api:
    needs: [ build-and-push-office-public-api ]
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/office/public-be/deploy/office-public-api-deploy.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      request_memory: 512Mi
      request_cpu: 250m
  
  web-public-be-apply-ingress:
    needs: [ deploy-office-public-api ]
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/office/public-be/apply-ingress/web-public-apply-ingress.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}