name: Apply web public FE ingress

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        
jobs:
  apply-ingress:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'
          
      - name: Apply web public FE ingress
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          envsubst < k8s/ingress/termodom-web-public-fe-ingress.yaml | kubectl apply -f -
          envsubst < k8s/ingress/root/termodom-web-public-fe-ingress.yaml | kubectl apply -f -
