apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${DEPLOY_ENV}-office-public-api-ingress
  namespace: termodom-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - api-office-${DEPLOY_ENV}.termodom.rs
    secretName: star-termodom-tls
  rules:
  - host: api-office-${DEPLOY_ENV}.termodom.rs
    http:
      paths:
#      - path: /interne-otpremnice
#        pathType: Prefix
#        backend:
#          service:
#            name: ${DEPLOY_ENV}-office-interne-otpremnice-api-service
#            port:
#              number: 81
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${DEPLOY_ENV}-office-public-api-service
            port:
              number: 80