apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${DEPLOY_ENV}-quizz-fe-ingress
  namespace: termodom-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls:
  - hosts:
    - kviz-${DEPLOY_ENV}.termodom.rs
    secretName: star-termodom-tls
  rules:
  - host: kviz-${DEPLOY_ENV}.termodom.rs
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${DEPLOY_ENV}-quizz-fe-service
            port:
              number: 80
