apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${DEPLOY_ENV}-termodom-office-public-api-ingress
  namespace: termodom-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - api-office-${DEPLOY_ENV}.termodom.rs
    secretName: star-termodom-tls
  rules:
  - host: api-office-${DEPLOY_ENV}.termodom.rs
    http:
      paths:
      - path: /specifikacija-novca
        pathType: Prefix
        backend:
          service:
            name: ${DEPLOY_ENV}-termodom-office-public-api-service
            port:
              number: 81
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${DEPLOY_ENV}-termodom-office-public-api-service
            port:
              number: 80
