apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${DEPLOY_ENV}-web-admin-fe-ingress
  namespace: termodom-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - admin-${DEPLOY_ENV}.termodom.rs
    secretName: star-termodom-tls
  rules:
  - host: admin-${DEPLOY_ENV}.termodom.rs
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${DEPLOY_ENV}-web-admin-fe-service
            port:
              number: 80
