apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: termodom-public-fe-ingress
  namespace: termodom-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - stage.termodom.rs
    secretName: star-termodom-tls
  rules:
  - host: stage.termodom.rs
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: termodom-public-fe-service
            port:
              number: 80
