name: Release web applications

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        
jobs:
  public-be:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/web/public-be/release-web-public-be.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      
  public-fe:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/web/public-fe/release-web-public-fe.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      
  admin-be:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/web/admin-be/release-web-admin-be.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      
  admin-fe:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/web/admin-fe/release-web-admin-fe.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}