name: Release web public FE applications

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  build-and-push-web-public-fe:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/web/public-fe/build-and-push-images/web-public-fe-build-and-push-image.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}
  
  deploy-web-public-fe:
    needs: [ build-and-push-web-public-fe ]
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/web/public-fe/deploy/web-public-fe-deploy.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}
  
  web-public-fe-apply-ingress:
    needs: [ deploy-web-public-fe ]
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/web/public-fe/apply-ingress/web-public-fe-apply-ingress.yml@master
    secrets: inherit
    with:
      env: ${{ inputs.env }}