apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOY_ENV}-office-public-fe-deployment
  namespace: termodom-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOY_ENV}-office-public-fe
  template:
    metadata:
      labels:
        app: ${DEPLOY_ENV}-office-public-fe
    spec:
      containers:
      - name: ${DEPLOY_ENV}-office-public-fe
        image: limitlesssoft/termodom-office-public-fe:${DEPLOY_ENV}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
#          - name: NEXT_PUBLIC_API_BASE_MAIN_URL
#            value: "https://api-office-${DEPLOY_ENV}.termodom.rs"
      imagePullSecrets:
      - name: regcred