apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOY_ENV}-termodom-web-public-fe-deployment
  namespace: termodom-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOY_ENV}-termodom-web-public-fe
  template:
    metadata:
      labels:
        app: ${DEPLOY_ENV}-termodom-web-public-fe
    spec:
      containers:
      - name: ${DEPLOY_ENV}-termodom-web-public-fe
        image: limitlesssoft/termodom-web-public-fe:${DEPLOY_ENV}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NEXT_PUBLIC_API_BASE_MAIN_URL
          value: "https://api-${DEPLOY_ENV}.termodom.rs"
        - name: NEXT_PUBLIC_POSTHOG_KEY
          value: ${POSTHOG_KEY}
        - name: NEXT_PUBLIC_POSTHOG_HOST
          value: ${POSTHOG_HOST}
      imagePullSecrets:
      - name: regcred