apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOY_ENV}-termodom-web-postgres-deployment
  namespace: termodom-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOY_ENV}-termodom-web-postgres
  template:
    metadata:
      labels:
        app: ${DEPLOY_ENV}-termodom-web-postgres
    spec:
      containers:
      - name: ${DEPLOY_ENV}-termodom-web-postgres
        image: postgres:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432