apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOY_ENV}-termodom-web-public-api-deployment
  namespace: termodom-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOY_ENV}-termodom-web-public-api
  template:
    metadata:
      labels:
        app: ${DEPLOY_ENV}-termodom-web-public-api
    spec:
      containers:
      - name: ${DEPLOY_ENV}-termodom-web-public-api
        image: limitlesssoft/termodom-web-public-api:${DEPLOY_ENV}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred