apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOY_ENV}-office-pregled-i-uplata-pazara-service
  namespace: termodom-namespace
spec:
  selector:
    app: ${DEPLOY_ENV}-office-pregled-i-uplata-pazara
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8080
  type: NodePort