apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOY_ENV}-quizz-fe-service
  namespace: termodom-namespace
spec:
  selector:
    app: ${DEPLOY_ENV}-quizz-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort