apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOY_ENV}-office-public-specifikacija-novca-micro-service
  namespace: termodom-namespace
spec:
  selector:
    app: ${DEPLOY_ENV}-office-public-specifikacija-novca
  ports:
  - protocol: TCP
    port: 81
    targetPort: 3000
  type: NodePort