apiVersion: v1
kind: Service
metadata:
  name: termodom-public-api-service
  namespace: termodom-namespace
spec:
  selector:
    app: termodom-public-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort