apiVersion: v1
kind: Service
metadata:
  name: termodom-public-fe-service
  namespace: termodom-namespace
spec:
  selector:
    app: termodom-public-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort