name: Test Automation - UAT

on:
    workflow_dispatch:
    pull_request:
        types:
            - labeled
            - unlabeled
            - opened
            - synchronize
            - reopened
        branches:
            - feature/#1884

jobs:
    check-if-ready-for-testing:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - uses: mheap/github-action-required-labels@v5
              with:
                  mode: exactly
                  count: 1
                  labels: |
                      automation-testing-ready
                  add_comment: true
                  message: 'This pipeline is canceled because pull request lacks automation-testing-ready label. If your PR is ready to be merged, add the label and pipeline will be automatically ran. Only after passing all tests, PR will be merged.'
    uat-web-public:
        needs: [check-if-ready-for-testing]
        uses: limitlesssoft/termodom--ecosystem/.github/workflows/test-automation-uat-web-public.yml@feature/test-pipeline-aleksa
        secrets: inherit
    uat-office-public:
        needs: [check-if-ready-for-testing]
        uses: limitlesssoft/termodom--ecosystem/.github/workflows/test-automation-uat-office-public.yml@feature/test-pipeline-aleksa
        secrets: inherit
    uat-web-admin:
        needs: [check-if-ready-for-testing]
        uses: limitlesssoft/termodom--ecosystem/.github/workflows/test-automation-uat-web-admin.yml@feature/test-pipeline-aleksa
        secrets: inherit
