name: Build and push build-and-push-termodom-inactive-users-checkup-cron-job docker image, then start deploying action

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  build-and-push-termodom-inactive-users-checkup-cron-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone repository
      run: |
        login to github
        git clone [url]