name: Build and push termodom-web-public-fe application docker image, then start deploying action

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    
jobs:
  build-and-push-termodom-web-public-fe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log DOCKER_HUB_USERNAME
      run: echo ${{ secrets.DOCKER_HUB_USERNAME }}
      
    - name: LOG POSTHOG_HOST
      shell: bash
      env: 
        POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
      run: |
        echo ${{ env.POSTHOG_HOST }}
        echo ${{ toJson(inputs) }}
        echo ${{ toJson(env) }}

    - name: Build docker image
<<<<<<< HEAD
      env:
        POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
        POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
      run: docker build --file src/TD.Web/TD.Web.Public/TD.Web.Public.Fe/Dockerfile --build-arg="DEPLOY_ENV=${{ inputs.env }}" --build-arg="POSTHOG_HOST=$POSTHOG_HOST" --build-arg="POSTHOG_KEY=$POSTHOG_KEY" -t limitlesssoft/termodom-web-public-fe:${{ inputs.env }} .
=======
      run: docker build --file src/TD.Web/TD.Web.Public/TD.Web.Public.Fe/Dockerfile --build-arg="DEPLOY_ENV=${{ inputs.env }}" -t limitlesssoft/termodom-web-public-fe:${{ inputs.env }} .
>>>>>>> parent of d296ee88 (Deployment hotfix posthog)

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push docker image
      run: docker push limitlesssoft/termodom-web-public-fe:${{ inputs.env }}
      
  deploy:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/deploy-termodom-web-public-fe.yml@master
    needs: [ build-and-push-termodom-web-public-fe ]
    secrets: inherit
    with:
      env: ${{ inputs.env }}
