name: Build and push termodom-web-public-api application docker image, then start deploying action

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      request_memory:
        required: true
        type: string
      request_cpu:
        required: true
        type: string
    
jobs:
  build-and-push-termodom-web-public-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      run: docker build --file src/TD.Web/TD.Web.Public/TD.Web.Public.Api/Dockerfile -t limitlesssoft/termodom-web-public-api:${{ inputs.env }} .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push docker image
      run: docker push limitlesssoft/termodom-web-public-api:${{ inputs.env }}
      
  deploy:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/deploy-termodom-web-public-api.yml@develop
    needs: [ build-and-push-termodom-web-public-api ]
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      request_memory: ${{ inputs.request_memory }}
      request_cpu: ${{ inputs.request_cpu }}
