name: Deploy termodom-office-public-api application to cluster
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
jobs:
  apply-resources:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
    
    - uses: actions/checkout@v3

    - name: Set K8s context
      uses: ossrs/k8s-set-context-action@v1
      with:
        kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'
      
    - name: Deploy termodom-office-public-api application
      run: |-
        export VAULT_URI=${{ secrets.VAULT_URI }}
        export VAULT_USERNAME=${{ secrets.VAULT_USERNAME }}
        export VAULT_PASSWORD=${{ secrets.VAULT_PASSWORD }}
        export VAULT_ENGINE=${{ secrets.VAULT_ENGINE }}
        export VAULT_PATH=${{ secrets.VAULT_PATH }}
        
        envsubst < k8s/services/termodom-office-public-api-service.yaml | kubectl apply -f -
        
        envsubst < k8s/deployments/termodom-office-public-api-deployment.yaml | kubectl apply -f -
        
        envsubst < k8s/ingress/termodom-office-public-api-ingress.yaml | kubectl apply -f -
        envsubst < k8s/ingress/root/termodom-office-public-api-ingress.yaml | kubectl apply -f -
        
        kubectl rollout restart -n termodom-namespace deployment ${{ inputs.env }}-termodom-office-public-api-deployment
