name: Deploy termodom-office-public-api application to cluster
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
jobs:
  apply-resources:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
    
    - uses: actions/checkout@v3

    - name: Set K8s context
      uses: ossrs/k8s-set-context-action@v1
      with:
        kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'
          
    - name: Deploy termodom-office-public-api application
      run: |-
        export DEPLOY_ENV=${{ inputs.env }}
        export JWT_ISSUER=${{ vars.JWT_ISSUER }}
        export JWT_AUDIENCE=${{ vars.JWT_AUDIENCE }}
        export JWT_KEY=${{ secrets.JWT_KEY }}
        export POSTGRES_HOST=${{ vars.POSTGRES_HOST }}
        export POSTGRES_PORT=${{ vars.POSTGRES_PORT }}
        export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        export POSTGRES_DATABASE_NAME=${{ vars.OFFICE_POSTGRES_DATABASE_NAME }}
        export TD_WEB_API_URL=${{ vars.TD_WEB_API_URL }}
        
#        envsubst < k8s/services/termodom-office-public-specifikacija-novca-micro-service.yaml | kubectl apply -f -
        envsubst < k8s/services/termodom-office-public-api-service.yaml | kubectl apply -f -
        
        envsubst < k8s/deployments/termodom-office-public-api-deployment.yaml | kubectl apply -f -
#        envsubst < k8s/deployments/termodom-office-public-specifikacija-novca-microservice-deployment.yaml | kubectl apply -f -
        
        envsubst < k8s/ingress/termodom-office-public-api-ingress.yaml | kubectl apply -f -
        envsubst < k8s/ingress/root/termodom-office-public-api-ingress.yaml | kubectl apply -f -
        
        kubectl rollout restart -n termodom-namespace deployment ${{ inputs.env }}-termodom-office-public-api-deployment
#        kubectl rollout restart -n termodom-namespace deployment ${{ inputs.env }}-office-public-specifikacija-novca-deployment
