name: TD.Komercijalno.Tests

on:
  pull_request:
    branches: [ "master", "stage", "develop" ]
    paths:
      - 'src/TD.Komercijalno/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore src/TD.Komercijalno/TD.Komercijalno.Tests/TD.Komercijalno.Tests.csproj

    - name: Build
      run: dotnet build src/TD.Komercijalno/TD.Komercijalno.Tests/TD.Komercijalno.Tests.csproj --no-restore

    - name: Test
      run: dotnet test src/TD.Komercijalno/TD.Komercijalno.Tests/TD.Komercijalno.Tests.csproj --no-build --verbosity normal
