name: Release develop termodom-web-admin

on:
  workflow_call:
  push:
    branches: [ "develop" ]
    
jobs:
  develop-api:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/build-and-push-termodom-web-admin-api.yml@develop
    secrets: inherit
    with:
      env: develop

  develop-fe:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/build-and-push-termodom-web-admin-fe.yml@develop
    secrets: inherit
    with:
      env: develop
