name: Release web admin fe application

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  build-and-push-image:
    name: Build and push web admin FE application image
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker build --file src/TD.Web/TD.Web.Admin/TD.Web.Admin.Fe/Dockerfile --build-arg="DEPLOY_ENV=${{ inputs.env }}" -t limitlesssoft/termodom-web-admin-fe:${{ inputs.env }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push docker image
        run: docker push limitlesssoft/termodom-web-admin-fe:${{ inputs.env }}

  deploy:
    needs: [build-and-push-image]
    name: Deploy web admin FE application
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'
          
      - name: Deploy termodom-web-admin-fe application
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          envsubst < k8s/services/termodom-web-admin-fe-service.yaml | kubectl apply -f -
          envsubst < k8s/deployments/termodom-web-admin-fe-deployment.yaml | kubectl apply -f -
          kubectl rollout restart -n termodom-namespace deployment ${{ inputs.env }}-web-admin-fe-deployment
          
  setup-ingress:
    needs: [deploy]
    name: Setup web admin ingress
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3
        
      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'

      - name: Setup ingress
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          envsubst < k8s/ingress/termodom-web-admin-fe-ingress.yaml | kubectl apply -f -
          envsubst < k8s/ingress/root/termodom-web-admin-fe-ingress.yaml | kubectl apply -f -