name: Release office public BE applications

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  build-and-push-public-api-image:
    name: Build and push office public api application image
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Build .NET API docker image
        run: docker build --file src/TD.Office/TD.Office.Public/TD.Office.Public.Api/Dockerfile -t limitlesssoft/termodom-office-public-api:${{ inputs.env }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push .NET API docker image
        run: docker push limitlesssoft/termodom-office-public-api:${{ inputs.env }}
        
  build-and-push-interne-otpremnice-api-image:
    name: Build and push office interne otpremnice api application image
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Build .NET API docker image
        run: docker build --file src/TD.Office/TD.Office.InterneOtpremnice/TD.Office.InterneOtpremnice.Api/Dockerfile -t limitlesssoft/termodom-office-interne-otpremnice-api:${{ inputs.env }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push .NET API docker image
        run: docker push limitlesssoft/termodom-office-interne-otpremnice-api:${{ inputs.env }}
  build-and-push-mass-sms-api-image:
    name: Build and push office mass sms api application image
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Build .NET API docker image
        run: docker build --file src/TD.Office/TD.Office.MassSMS/TD.Office.MassSMS.Api/Dockerfile -t limitlesssoft/termodom-office-mass-sms-api:${{ inputs.env }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push .NET API docker image
        run: docker push limitlesssoft/termodom-office-mass-sms-api:${{ inputs.env }}
  deploy-interne-otpremnice-api:
    needs: [build-and-push-interne-otpremnice-api-image]
    name: Deploy office interne-otpremnice api application
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'
          
      - name: Deploy termodom-office-interne-otpremnice-api application
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          export VAULT_URI=${{ secrets.VAULT_URI }}
          export VAULT_USERNAME=${{ secrets.VAULT_USERNAME }}
          export VAULT_PASSWORD=${{ secrets.VAULT_PASSWORD }}
          export VAULT_ENGINE=${{ vars.VAULT_ENGINE }}
          export VAULT_PATH=${{ vars.VAULT_PATH_OFFICE_INTERNE_OTPREMNICE_API }}
          
          envsubst < k8s/services/office-interne-otpremnice-api-service.yaml | kubectl apply -f -
          envsubst < k8s/deployments/office-interne-otpremnice-api-deployment.yaml | kubectl apply -f -
          kubectl rollout restart -n termodom-namespace deployment ${{ inputs.env }}-office-interne-otpremnice-api-deployment
  deploy-public-api:
    needs: [build-and-push-public-api-image]
    name: Deploy office public api application
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'

      - name: Deploy termodom-office-public-api application
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          export VAULT_URI=${{ secrets.VAULT_URI }}
          export VAULT_USERNAME=${{ secrets.VAULT_USERNAME }}
          export VAULT_PASSWORD=${{ secrets.VAULT_PASSWORD }}
          export VAULT_ENGINE=${{ vars.VAULT_ENGINE }}
          export VAULT_PATH_OFFICE_PUBLIC_API=${{ vars.VAULT_PATH_OFFICE_PUBLIC_API }}

          envsubst < k8s/services/office-public-api-service.yaml | kubectl apply -f -
          envsubst < k8s/deployments/office-public-api-deployment.yaml | kubectl apply -f -
          kubectl rollout restart -n termodom-namespace deployment ${{ inputs.env }}-office-public-api-deployment
  deploy-mass-sms-api:
    needs: [build-and-push-mass-sms-api-image]
    name: Deploy office mass sms api application
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'

      - name: Deploy termodom-office-mass-sms-api application
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          export VAULT_URI=${{ secrets.VAULT_URI }}
          export VAULT_USERNAME=${{ secrets.VAULT_USERNAME }}
          export VAULT_PASSWORD=${{ secrets.VAULT_PASSWORD }}
          export VAULT_ENGINE=${{ vars.VAULT_ENGINE }}
          export VAULT_PATH=${{ vars.VAULT_PATH_OFFICE_MASS_SMS_API }}

          envsubst < k8s/services/office-mass-sms-api-service.yaml | kubectl apply -f -
          envsubst < k8s/deployments/office-mass-sms-api-deployment.yaml | kubectl apply -f -
          kubectl rollout restart -n termodom-namespace deployment ${{ inputs.env }}-office-mass-sms-api-deployment
  setup-ingress:
    needs: [deploy-public-api, deploy-interne-otpremnice-api]
    name: Setup office public ingress
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3
        
      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'

      - name: Setup ingress
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          envsubst < k8s/ingress/office-public-api-ingress.yaml | kubectl apply -f -
          envsubst < k8s/ingress/root/office-public-api-ingress.yaml | kubectl apply -f -