name: Release web public BE applications

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  build-and-push-image:
    name: Build and push web public api application image
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker build --file src/TD.Web/TD.Web.Public/TD.Web.Public.Api/Dockerfile -t limitlesssoft/termodom-web-public-api:${{ inputs.env }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push docker image
        run: docker push limitlesssoft/termodom-web-public-api:${{ inputs.env }}

  deploy:
    needs: [build-and-push-image]
    name: Deploy web public api application
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'

      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URI }}
          method: userpass
          username: ${{ secrets.VAULT_USERNAME }}
          password: ${{ secrets.VAULT_PASSWORD }}
          secrets: |
            ${{ inputs.env }}/data/web/public/api POD_REQUEST_CPU | POD_REQUEST_CPU ;
            ${{ inputs.env }}/data/web/public/api POD_REQUEST_MEMORY | POD_REQUEST_MEMORY ;

      - name: Deploy termodom-web-public-api application
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          export VAULT_URI=${{ secrets.VAULT_URI }}
          export VAULT_USERNAME=${{ secrets.VAULT_USERNAME }}
          export VAULT_PASSWORD=${{ secrets.VAULT_PASSWORD }}
          export VAULT_ENGINE=${{ vars.VAULT_ENGINE }}
          export VAULT_PATH_WEB_PUBLIC_API=${{ vars.VAULT_PATH_WEB_PUBLIC_API }}
          export REQUEST_MEMORY=${{ env.POD_REQUEST_MEMORY }}
          export REQUEST_CPU=${{ env.POD_REQUEST_CPU }}
          
          envsubst < k8s/services/termodom-web-public-api-service.yaml | kubectl apply -f -
          envsubst < k8s/deployments/termodom-web-public-api-deployment.yaml | kubectl apply -f -
          kubectl rollout restart -n termodom-namespace deployment ${{ inputs.env }}-web-public-api-deployment
      
  setup-ingress:
    needs: [deploy]
    name: Setup web public ingress
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3
        
      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'

      - name: Setup ingress
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          envsubst < k8s/ingress/termodom-web-public-api-ingress.yaml | kubectl apply -f -
          envsubst < k8s/ingress/root/termodom-web-public-api-ingress.yaml | kubectl apply -f -