name: Release stage termodom-web-public
on:
  workflow_call:
  push:
    branches: [ "stage" ]
    
jobs:
  stage-api:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/build-and-push-termodom-web-public-api.yml@stage
    secrets: inherit
    with:
      env: stage

  stage-fe:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/build-and-push-termodom-web-public-fe.yml@stage
    secrets: inherit
    with:
      env: stage
