name: Release order status check cron

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  build-and-push-image:
    name: Build and push order status check cron
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker build --file src/TD.Cron/TD.Cron.OrderStatusCheckCronJob/Dockerfile -t limitlesssoft/td-cron-order-status-check-cron-job:${{ inputs.env }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push docker image
        run: docker push limitlesssoft/td-cron-order-status-check-cron-job:${{ inputs.env }}
        
  deploy:
    needs: [build-and-push-image]
    name: Deploy order status check cron
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Set K8s context
        uses: ossrs/k8s-set-context-action@v1
        with:
          kubeconfig: '${{ secrets.KUBE_CONFIG_PURE }}'
          
      - name: Deploy termodom-office-public-api application
        run: |-
          export DEPLOY_ENV=${{ inputs.env }}
          export VAULT_URI=${{ secrets.VAULT_URI }}
          export VAULT_USERNAME=${{ secrets.VAULT_USERNAME }}
          export VAULT_PASSWORD=${{ secrets.VAULT_PASSWORD }}
          export VAULT_ENGINE=${{ secrets.VAULT_ENGINE }}
          export VAULT_PATH=${{ secrets.VAULT_PATH }}
          envsubst < k8s/cronjobs/termodom-realized-orders-cron-job.yaml | kubectl apply -f -