name: Release stage termodom-web-public-fe

on:
  workflow_call:
  push:
    branches: [ "stage" ]
    
jobs:
  deploy:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/build-and-push-termodom-web-public-fe.yml@stage
    secrets: inherit
    with:
      env: stage
