name: Test implementation code

on:
    workflow_dispatch:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        branches:
            - feature/#1887

jobs:
    uat-web-public:
        uses: limitlesssoft/termodom--ecosystem/.github/workflows/test-public-fe.yml@feature/#1887
        secrets: inherit
        with:
            browser: chrome
