name: Web Deploy
on: [  push ]
jobs:
  deploy:
    name: CloudFormation script Run
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::697692391944:role/td-cloudformation-role
        aws-region: eu-central-1
    - name: Deploy to AWS Cloudformation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: Web Stack
        template: cloudformation/termodom-web-cloudformation.yml
