name: TD.Web.Public.Api Tests

on:
  pull_request:
    branches: [ "master" ] # "stage", "develop"
    paths:
      - 'src/TD.Web/TD.Web.Public/**'
      - 'src/TD.Web/TD.Web.Common/**'
  workflow_dispatch:

jobs:
  TD-Web-Public-Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore src/TD.Web/TD.Web.Public/TD.Web.Public.Tests/TD.Web.Public.Tests.csproj

    - name: Build
      run: dotnet build src/TD.Web/TD.Web.Public/TD.Web.Public.Tests/TD.Web.Public.Tests.csproj --no-restore

    - name: Test
      run: dotnet test src/TD.Web/TD.Web.Public/TD.Web.Public.Tests/TD.Web.Public.Tests.csproj --no-build --verbosity normal
