name: TD.Web.Admin.FE Tests

on:
  pull_request:
    branches: ["master", "stage", "develop"]
    paths:
      - 'src/TD.Web/TD.Web.Admin/TD.Web.Admin.Fe/**'
      - '.github/workflows/web-admin-fe-tests.yml'
  workflow_dispatch:

jobs:
  TD-Web-Admin-FE-Tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/TD.Web/TD.Web.Admin/TD.Web.Admin.Fe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'src/TD.Web/TD.Web.Admin/TD.Web.Admin.Fe/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci
